### ISSUE TITLE
Please consider moving the panel down the screen for mobile devices

### ISSUE THREAD

**Issue by VlaK0r** [Athou/commafeed#1121]
Hello!
Thanks for your project.

Please consider moving the panel down the screen for mobile devices.
Or consider other more convenient options for switching to the next entry on a mobile device.
For example, a floating button.

**Comment by poblabs** [comment]
As something that may get you by as a quick "fix", try the CSS code below. Go to Settings > Custom Code and enter this in CSS. If it doesn't seem quite-right to you and your needs, adjust some of the "bottom" positioning. 

It will mess up your top-of-screen alignment. Not sure how to fix that.

Note: I tried this on self-hosted

```css
@media (max-width: 1024px) {
    .mantine-Header-root {
        position: fixed !important;
        top: initial !important;
        left: 0;
        bottom: 2rem;
        text-align: right;
    }
    .mantine-AppShell-main {
        padding-top: 0 !important;
    }
}
```
