### ISSUE TITLE
5.0.0 is no longer usable on my server

### ISSUE THREAD

**Issue by NightHawkATL** [Athou/commafeed#1524]
**Describe the bug**
Lots of support issues with a processor that I have been using for some time. 
![image](https://github.com/user-attachments/assets/5fc9d542-1cb6-41b0-aa8a-0ab7fd8fb0c5)

**To Reproduce**
Upgrade to the latest with the above CPU

**Expected behavior**
That I would still be able to use it after the upgrade

**Screenshots**
![image](https://github.com/user-attachments/assets/f43fe098-31b1-495d-84a5-5252f52118f3)

**Environment (please complete the following information):**

- CommaFeed version 5.0.0
- Browser : Firefox
- Device : desktop & mobile

**Additional context**
Guess I'll have to stay on the older version until this is fixed or not.

**Comment by Athou** [comment]
I added the [quarkus.native.march=compatibility](https://quarkus.io/guides/building-native-image#quarkus-native-pkg-native-config_quarkus-native-march), do you mind testing with the binary from [this CI build](https://github.com/Athou/commafeed/actions/runs/10447514673)/the docker `master-<database>` tag? If it works I'll release 5.0.1.

**Comment by Athou** [comment]
Sorry, maybe I wasn't clear. Only binaries are published on that page, Docker CI builds are published directly on Docker Hub with the `master-<database>` tag.

**Comment by NightHawkATL** [comment]
sorry. will work on that.

**Comment by NightHawkATL** [comment]
I was able to get "master-postgresql" to load for me. It works with my processor now.

I also noticed that the new compose didn't mention a volume for the commafeed service and there is no longer mention of PGID & PUID but I added all of that to my stack for deployment.

```
services:
  commafeed:
    image: athou/commafeed:master-postgresql
    restart: unless-stopped
    container_name: commafeed
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgresql:5432/commafeed
      - QUARKUS_DATASOURCE_USERNAME=commafeed
      - QUARKUS_DATASOURCE_PASSWORD=*Redacted*
      - PGID=1000
      - PUID=1000
    volumes:
      - /portainer/Files/AppData/Config/commafeed/data:/commafeed/data
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - 8082:8082

  postgresql:
    image: postgres:latest
    container_name: commafeed_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: commafeed
      POSTGRES_PASSWORD: *Redacted*
      POSTGRES_DB: commafeed
      PGID: 1000
      PUID: 1000
    volumes:
      - /portainer/Files/AppData/Config/commafeed/db:/var/lib/postgresql/data
```
