### ISSUE TITLE
Problem with starting the Docker version

### ISSUE THREAD

**Issue by Goatmaster** [Athou/commafeed#1584]
Hey,

I have problems with the newest version of commafeed.

I am using it with docker compose an it worked fine before.
The latest verison that worked for me was 5.2.0. I skipped the 5.3.0 and tried it now with version 5.3.1.

Now I get a "unable to connect" error.

Here is my docker-compose.yml file.

```
services:
  commafeed:
    image: athou/commafeed:latest-postgresql
    restart: unless-stopped
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgresql:5432/commafeed
      - QUARKUS_DATASOURCE_USERNAME=commafeed
      - QUARKUS_DATASOURCE_PASSWORD=commafeed
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - 8082:8082

  postgresql:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: commafeed
      POSTGRES_PASSWORD: commafeed
      POSTGRES_DB: commafeed
    volumes:
      - /path/to/commafeed/db:/var/lib/postgresql/data
```

Would be nice to get it running again.

Thank you.
