### ISSUE TITLE
Change orange color.

### ISSUE THREAD

**Issue by tiritibambix** [Athou/commafeed#1598]
Would it be possible to have an option to change the general orange color theme ?
It would be awesome :)

**Comment by srt19170** [comment]
Adding

`header svg {stroke: black !important; }`
`main > div > div svg {stroke: black !important; }`

to the custom CSS code will change the various SVG icons to black.  Changing the background colors of the buttons, highlight colors, etc. can probably also be changed this way, but I haven't bothered to figure that out.

**Comment by DarkFox** [comment]
I've made a more complete custom style to override most of the colours. I'm sure there's a bit of duplicated effort in there, but it's working.

```css
:root {
    --custom-dark-color: blueviolet;
    --custom-medium-color: mediumpurple;
    --custom-light-color: thistle;
    --custom-transparent-color: #8A2BE233;
    --custom-logo-hue-rotate: 220deg;

    --mantine-color-anchor: var(--custom-dark-color) !important;
    --mantine-color-orange-light: var(--custom-light-color) !important;
    --mantine-color-orange-light-color: var(--custom-dark-color) !important;
    --mantine-color-orange-filled: var(--custom-dark-color) !important;
    --mantine-color-orange-light-hover: var(--custom-transparent-color) !important;
    --tabs-color: var(--custom-dark-color) !important;
    --badge-bg: var(--custom-light-color) !important;
    --badge-color: var(--custom-dark-color) !important;
    --button-color: var(--custom-dark-color) !important;
    --button-bg: var(--custom-medium-color) !important;
    --button-hover: var(--custom-light-color) !important;
}

header svg {stroke: var(--custom-dark-color) !important; }
main > div > div svg {stroke: var(--custom-dark-color) !important; }
main .selected.show-selection-indicator { border-left-color: var(--custom-light-color) !important; }

header#header.mantine-AppShell-header div.mantine-Center-root img.mantine-Image-root {
    filter: hue-rotate(var(--custom-logo-hue-rotate));
}
```
