### ISSUE TITLE
Internal Server Error: When running the latest version of postgres

### ISSUE THREAD

**Issue by tdmarchetta** [Athou/commafeed#1633]
**Describe the bug**

Every time I run “docker-compose pull && docker-compose up -d”
Using the latest version I receive error message “Internal Server Error
Error id 81825681-4793-47c0-8034-b4dca5c9efe5-4”

**To Reproduce**

image: postgres:16.4

**Expected behavior**
In the web browser, I would expect to be able to log in using my credentials on the main splash page.

**Screenshots**

**Environment (please complete the following information):**

Linux Ubuntu 22.04
Docker 27.2.1

```
services:
  commafeed:
    image: athou/commafeed:latest-postgresql
    restart: unless-stopped
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgresql:5432/commafeed
      - QUARKUS_DATASOURCE_USERNAME=commafeed
      - QUARKUS_DATASOURCE_PASSWORD=Password
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - 8082:8082

  postgresql:
    #image: postgres:16.4 # Running older version of postgres... Latest version kill apps...
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: commafeed
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: commafeed
    volumes:
      - ./commafeed/db:/var/lib/postgresql/data
```

- commafeed.com or self-hosted:
- If self-hosted, CommaFeed version [e.g. 5.1.0 (a3dcb2c)]:
- Browser [e.g. chrome, firefox]: Brave, Firefox, Chrome
- Device [e.g. desktop, mobile]: Desktop

**Additional context**

Any help would be much appreciated!!
