### ISSUE TITLE
Run commafeed in a folder  (my.host.com/commafeed)

### ISSUE THREAD

**Issue by cudeso** [Athou/commafeed#1816]
Hello.
I'm trying to get Commafeed to run out of a folder location but always ending up with the "**Resource not found**" error. Accessing it directly via its own (sub-)domain works flawlessly. Commafeed is started via Docker with an NGINX proxy (also in Docker) in front of it. In the `docker-compose.yml` I set 

```
      - COMMAFEED_APP_PUBLICURL="https://my.host.com/commafeed/"
```

The NGINX config is below. Any suggestion where to look for to set the publicurl correctly?

```
                location /commafeed/ {
                        proxy_pass http://commafeed:8082;
                        proxy_read_timeout 300s;
                        proxy_connect_timeout 75s;
                        proxy_http_version                 1.1;
                        proxy_cache_bypass                 $http_upgrade;
                        proxy_ssl_verify off;
                        proxy_set_header Upgrade           $http_upgrade;
                        proxy_set_header Connection        "upgrade";
                        proxy_set_header Host              $host;
                        proxy_set_header X-Real-IP         $remote_addr;
                        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
                        proxy_set_header X-Forwarded-Proto $scheme;
                        proxy_set_header X-Forwarded-Host  $host;
                        proxy_set_header X-Forwarded-Port  $server_port;

                }
```

**Comment by Athou** [comment]
I haven't tried but setting `QUARKUS_HTTP_ROOT_PATH` to `/commafeed` should work (see [here](https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus-http-root-path) for reference).

You should then change your `proxy_pass` config to `proxy_pass http://commafeed:8082/commafeed`;

EDIT: nevermind, this variable is evaluated at build time and has no effect at runtime. By the way, `COMMAFEED_APP_PUBLICURL` no longer exists since v5.0, and was only used to redirect users to the right url after some specific actions. 

I'm not sure what your issue is, I'll have to replicate this environment locally with nginx to see for myself. Have you tried using a `location` directive without a trailing slash? I know that the trailing slash has a specific meaning with nginx.

**Comment by Athou** [comment]
Here's a working example:

docker-compose.yml
```yml
services:
  commafeed:
    image: athou/commafeed:latest-h2
    ports:
      - 8082:8082
  nginx:
    image: nginx:latest
    ports:
      - 8083:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - commafeed
```

nginx.conf
```nginx
server {
    location /commafeed/ {
        proxy_pass http://commafeed:8082/;
    }
}
```

CommaFeed is then accessible on http://localhost:8083/commafeed/

**Comment by cudeso** [comment]
Hello @Athou 
I had to adjust the example to the below config

For **docker-compose.yml** (I haven't checked if `QUARKUS_HTTP_ROOT_PATH` is still needed)
```
  commafeed:
    hostname: commafeed
    container_name: commafeed
    image: athou/commafeed:master-mariadb
    restart: unless-stopped
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mariadb://${MYSQL_HOST}/${MYSQL_COMMAFEED_DATABASE}?autoReconnect=true&failOverReadOnly=false&maxReconnects=20&rewriteBatchedStatements=true&timezone=UTC
      - QUARKUS_DATASOURCE_USERNAME=${MYSQL_COMMAFEED_USER}
      - QUARKUS_DATASOURCE_PASSWORD=${MYSQL_COMMAFEED_PASSWORD}
      - COMMAFEED_APP_PUBLICURL="https://${COMMAFEED_HOST}/commafeed/"
      - QUARKUS_HTTP_ROOT_PATH="/commafeed"
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - 8082:8082
```

For **nginx.conf** (the other proxy settings are basically the template used for other sites behind the rev proxy, might not all be needed for Commafeed
```
  location /commafeed/ {
          proxy_pass http://commafeed:8082/;
          proxy_read_timeout 300s;
          proxy_connect_timeout 75s;
          proxy_http_version                 1.1;
          proxy_cache_bypass                 $http_upgrade;
          proxy_ssl_verify off;
          proxy_set_header Upgrade           $http_upgrade;
          proxy_set_header Connection        "upgrade";
          proxy_set_header Host              $host;
          proxy_set_header X-Real-IP         $remote_addr;
          proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host  $host;
          proxy_set_header X-Forwarded-Port  $server_port;
  }
```

Maybe the config can be useful for others as well. 

Many thanks for the quick update to the image!
