### ISSUE TITLE
can support docker install?

### ISSUE THREAD

**Issue by wjx0912** [Athou/commafeed#895]
thanks

**Comment by emericv** [comment]
I have written a Dockerfile :
```Dockerfile
FROM openjdk:8-alpine
ARG COMMAFEED_VERSION

EXPOSE 8082

RUN echo Installing packages && \
    apk add \
      --no-cache \
      bash \
      wget

RUN wget https://github.com/Athou/commafeed/releases/download/$COMMAFEED_VERSION/commafeed.jar \
        --progress bar:force:noscroll --output-document commafeed.jar

CMD ["java", "-jar", "commafeed.jar", "server", "/config/config.yml"]
```

can be built with `docker build --build-arg COMMAFEED_VERSION=x.y.z .` or using the following build property in a docker-compose.yml:
```YAML
    build:
      context: ./commafeed/
      args:
        COMMAFEED_VERSION: x.y.z
```

**Comment by wjx0912** [comment]
@emericv thank you

**Comment by Dreomite** [comment]
Here's a minimal docker-compose setup for the latest Commafeed + PostgreSQL that can be used to run Commafeed localy. Maybe this will save someone 20-30 mins.

## Prerequisites

Dir contents:
```sh
.
├── docker-compose.yml
├── config.yml # Commafeed config
└── commafeed
	└── Dockerfile
```

### `./docker-compose.yml`

```yaml
version: "3"

services:

  db:
    image: postgres:13-alpine
    container_name: commafeed_db
    hostname: commafeed_db
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      # default values from config.yml
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=sa
      - POSTGRES_DB=commafeed

  app:
    build: ./commafeed
    container_name: commafeed
    hostname: commafeed
    restart: always
    ports:
      - "8082:8082"
    volumes:
      - ./config.yml:/config/config.yml:ro
      - sessions:/sessions

volumes:
  db:
  sessions:
```

### `./commafeed/Dockerfile`

```dockerfile
FROM openjdk:8

RUN wget https://github.com/Athou/commafeed/releases/latest/download/commafeed.jar \
        --progress bar:force:noscroll --output-document commafeed.jar

CMD ["java", "-Djava.net.preferIPv4Stack=true", "-jar", "commafeed.jar", "server", "/config/config.yml"]
```

## Steps

1. Download default config for your Commafeed version:
	```
	wget https://raw.githubusercontent.com/Athou/commafeed/2.5.0/config.yml.example -O ./config.yml
	```
2. Open it, and set appropriate database driver and query URL:
	```yaml
	database:
  	  driverClass: org.postgresql.Driver
	  # 'commafeed_db' is Postgres container's `hostname` 
  	  url: jdbc:postgresql://commafeed_db:5432/commafeed
	```
3. Run with
	```sh
	docker-compose up
	```

Commafeed instance will be available at http://localhost:8082. Default login/password is `admin`/`admin`.
